import { Injectable } from '@angular/core';
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor
} from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()
export class TokenInterceptor implements HttpInterceptor {

  constructor() {}

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    request = request.clone({
      setHeaders: {
        Authorization: `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5EZzRPRGd3TURKR05VVTJNVVJFTXpKRVFUYzFPVGs0TlVORE9UVkJRVGd3TXpCRFFUa3pNZyJ9.eyJodHRwczovL2FrZWxpdXMuY29tL2NsYWltcy91c2VyaWQiOiJhdXRoMHw1YTc4NTEyODY4NzY3NjM0Y2Y0NzA0NjQiLCJodHRwczovL2ludmVzdG1lbnQuYWtlbGl1cy5jb20vY2xhaW1zL3JvbGVzIjpbImludmVzdG1lbnRtYWtlci1ERSIsImludmVzdG1lbnRtYWtlci1GUiJdLCJodHRwczovL2FrZWxpdXMuY29tL2NsYWltcy9naXZlbl9uYW1lIjoiSmFuZSIsImh0dHBzOi8vYWtlbGl1cy5jb20vY2xhaW1zL2ZhbWlseV9uYW1lIjoiRG9lIiwiaHR0cHM6Ly9ha2VsaXVzLmNvbS9jbGFpbXMvZW1haWwiOiJhbGV4YW5kZXIuc2NoaWxwcEBha2VsaXVzLmRlIiwiaXNzIjoiaHR0cHM6Ly9ha2VsaXVzLWRldi5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWE3ODUxMjg2ODc2NzYzNGNmNDcwNDY0IiwiYXVkIjpbImh0dHBzOi8vaW52ZXN0bWVudC1kZXYuYWtlbGl1cy5jb20vYXBpLyIsImh0dHBzOi8vYWtlbGl1cy1kZXYuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTUzMTEzNzg5MSwiZXhwIjoxNTMxMTQ1MDkxLCJhenAiOiI1SzR4NGk3b1FObXhDcGhkN1JPZHVOWmN4YWZZTTc3VSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.ZOtXbXi0E4z4DGyqYw9mffDrUh6lDXsmsbQWUIBqZM3hw8WdR0immlx-9FNdGZqyNRpcwEuOpRywPsZQWWjcaTdATrwv37M5CsN-MLXBanMhLE9m3OMrqTf3pvJZcpZVaCrF6IPq7tSCGOA79RKvmpmvY4n8UgX0mkE02ptsrVVNL5Ve3pST7c-dpUm8PFCJqtpxs8XXgTRwSGLnILSRcqniiHmNZyjxdCLAVxzsZ-tPcyNYWXML_BV6yxZ-I2tKhJcPfXch3flcnU-SBLh2Qtsv5-R_nKKFKyBn1gwJF-LwS3qqBagpKV-FXwepiUcTr17mA4xx97rTfsP8GkxIAQ`
      }
    });
    return next.handle(request);
  }
}
